<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Organizacion;
use App\Models\Provincia;
use App\Models\Canton;
use App\Models\Distrito;
use App\Models\TipoOrganizacion;
use App\Models\User;

class OrganizacionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Organizacion::truncate();
        // Obtener tipos de organizaciones
        $tipoGobiernoLocal = TipoOrganizacion::where('nombre', 'Gobierno Local')->first();
        $tipoInstitucionPublica = TipoOrganizacion::where('nombre', 'Institucion Pública')->first();
        $tipoCooperativa = TipoOrganizacion::where('nombre', 'Cooperativa')->first();
        $tipoConsorcio = TipoOrganizacion::where('nombre', 'Consorcio')->first();
        $tipoONG = TipoOrganizacion::where('nombre', 'ONG')->first();
        
        $user = User::where('role', 'admin')->first();

        // Crear organizaciones de prueba con coordenadas correctas y diferentes categorías
        $organizaciones = [
            // MUNICIPALIDADES / GOBIERNO LOCAL
           [
        'ced_juridica' => '3014042063',
        'nombre' => 'Municipalidad de Alajuela',
        'tipo_id' => $tipoGobiernoLocal->id ?? 1,
        'telefono' => '24362300',
        'correo' => 'munialajuela.redsocial@munialajuela.go.cr',
        'urlPageWeb' => 'https://www.munialajuela.go.cr/',
        'provincia_id' => 2, // Alajuela
        'canton_id' => null,
        'distrito_id' => null,
        'ubi_Lat' => '10.0171412',
        'ubi_long' => '-84.210448',
        'urlDirectorioTelefonico' => 'https://www.munialajuela.go.cr/contactenos',
        'user_id' => $user->id ?? 1,
    ],
    [
        'ced_juridica' => '3014042065',
        'nombre' => 'Municipalidad de Atenas',
        'tipo_id' => $tipoGobiernoLocal->id ?? 1,
        'telefono' => '24465040',
        'correo' => 'comunicacion@atenasmuni.go.cr',
        'urlPageWeb' => 'https://www.atenasmuni.go.cr/',
        'provincia_id' => 2,
        'canton_id' => null,
        'distrito_id' => null,
        'ubi_Lat' => '9.9788536',
        'ubi_long' => '-84.3804325',
        'urlDirectorioTelefonico' => 'https://www.atenasmuni.go.cr/directoriomunicipal',
        'user_id' => $user->id ?? 1,
    ],
    [
        'ced_juridica' => '301404206412',
        'nombre' => 'Municipalidad de Grecia',
        'tipo_id' => $tipoGobiernoLocal->id ?? 1,
        'telefono' => '24956200',
        'correo' => 'alcaldia@grecia.go.cr',
        'urlPageWeb' => 'https://www.grecia.go.cr/',
        'provincia_id' => 2,
        'canton_id' => null,
        'distrito_id' => null,
        'ubi_Lat' => '10.0732811',
        'ubi_long' => '-84.3120192',
        'urlDirectorioTelefonico' => 'https://www.grecia.go.cr/contactos',
        'user_id' => $user->id ?? 1,
    ],

    [
        'ced_juridica' => '3014042067',
        'nombre' => 'Municipalidad de Guatuso',
        'tipo_id' => $tipoGobiernoLocal->id ?? 1,
        'telefono' => '24640065',
        'correo' => 'alcaldia@muniguatuso.go.cr',
        'urlPageWeb' => 'https://muniguatuso.go.cr/',
        'provincia_id' => 2,
        'canton_id' => null,
        'distrito_id' => null,
        'ubi_Lat' => '10.6698207',
        'ubi_long' => '-84.8216561',
        'urlDirectorioTelefonico' => 'https://muniguatuso.go.cr/index.php/centrodeinformacion/directoriotelefonicoguatuso.html',
        'user_id' => $user->id ?? 1,
    ],

    [
        'ced_juridica' => '3014042068',
        'nombre' => 'Municipalidad de Los Chiles',
        'tipo_id' => $tipoGobiernoLocal->id ?? 1,
        'telefono' => '24711038',
        'correo' => 'infotramites@muniloschiles.go.cr',
        'urlPageWeb' => 'https://www.muniloschiles.go.cr/',
        'provincia_id' => 2,
        'canton_id' => null,
        'distrito_id' => null,
        'ubi_Lat' => '11.030695',
        'ubi_long' => '-84.7174696',
        'urlDirectorioTelefonico' => 'https://www.muniloschiles.go.cr/index.php/mnconozcanos/mnmimunicipalidad/mndirectoriotelefonico',
        'user_id' => $user->id ?? 1,
    ],

    [
        'ced_juridica' => '3014042069',
        'nombre' => 'Municipalidad de Naranjo',
        'tipo_id' => $tipoGobiernoLocal->id ?? 1,
        'telefono' => '24515858',
        'correo' => 'informacion@naranjo.go.cr',
        'urlPageWeb' => 'https://www.naranjo.go.cr/',
        'provincia_id' => 2,
        'canton_id' => null,
        'distrito_id' => null,
        'ubi_Lat' => '10.0973049',
        'ubi_long' => '-84.3782054',
        'urlDirectorioTelefonico' => 'https://www.naranjo.go.cr/directorio/',
        'user_id' => $user->id ?? 1,
    ],

    [
        'ced_juridica' => '3014042073',
        'nombre' => 'Municipalidad de Poás',
        'tipo_id' => $tipoGobiernoLocal->id ?? 1,
        'telefono' => '24485060',
        'correo' => 'alcaldia@munipoas.go.cr',
        'urlPageWeb' => 'https://www.munipoas.go.cr/',
        'provincia_id' => 2,
        'canton_id' => null,
        'distrito_id' => null,
        'ubi_Lat' => '10.0765849',
        'ubi_long' => '-84.2458669',
        'urlDirectorioTelefonico' => 'https://munipoas.go.cr/index.php/conozcanos/mimunicipalidad/directoriotelefonico.html',
        'user_id' => $user->id ?? 1,
    ],

    [
        'ced_juridica' => '3014795871',
        'nombre' => 'Municipalidad de Río Cuarto',
        'tipo_id' => $tipoGobiernoLocal->id ?? 1,
        'telefono' => '40001600',
        'correo' => 'consultas@muniriocuarto.go.cr',
        'urlPageWeb' => 'https://www.muniriocuarto.go.cr/',
        'provincia_id' => 2,
        'canton_id' => null,
        'distrito_id' => null,
        'ubi_Lat' => '10.3460457',
        'ubi_long' => '-84.2136239',
        'urlDirectorioTelefonico' => 'https://www.muniriocuarto.go.cr/departamentos',
        'user_id' => $user->id ?? 1,
    ],

    [
        'ced_juridica' => '3014042076',
        'nombre' => 'Municipalidad de San Ramón',
        'tipo_id' => $tipoGobiernoLocal->id ?? 1,
        'telefono' => '24569400',
        'correo' => 'municipalidad@sanramon.go.cr',
        'urlPageWeb' => 'https://sites.google.com/sanramondigital.net/sanramongocr/páginaprincipal?authuser=0',
        'provincia_id' => 2,
        'canton_id' => null,
        'distrito_id' => null,
        'ubi_Lat' => '10.0877268',
        'ubi_long' => '-84.4702258',
        'urlDirectorioTelefonico' => 'https://sites.google.com/sanramondigital.net/sanramongocr/contáctenos?authuser=0',
        'user_id' => $user->id ?? 1,
    ],

    [
        'ced_juridica' => '3014042078',
        'nombre' => 'Municipalidad de Sarchí',
        'tipo_id' => $tipoGobiernoLocal->id ?? 1,
        'telefono' => '24544001',
        'correo' => 'plataformadeservicios@munisarchi.go.cr',
        'urlPageWeb' => 'https://www.munisarchi.go.cr/',
        'provincia_id' => 2,
        'canton_id' => null,
        'distrito_id' => null,
        'ubi_Lat' => '10.0892574',
        'ubi_long' => '-84.3486008',
        'urlDirectorioTelefonico' => 'https://www.munisarchi.go.cr/departamentos',
        'user_id' => $user->id ?? 1,
    ],

    // CARTAGO
    [
        'ced_juridica' => '3014042079',
        'nombre' => 'Municipalidad de Alvarado',
        'tipo_id' => $tipoGobiernoLocal->id ?? 1,
        'telefono' => '25344120',
        'correo' => 'concejo@munialvarado.go.cr',
        'urlPageWeb' => 'http://www.munialvarado.go.cr/',
        'provincia_id' => 3, // Cartago
        'canton_id' => null,
        'distrito_id' => null,
        'ubi_Lat' => '9.9162377',
        'ubi_long' => '-83.8105841',
        'urlDirectorioTelefonico' => 'http://www.munialvarado.go.cr/index.php/conozcanos/mimunicipalidad/directorioelectronico.html',
        'user_id' => $user->id ?? 1,
    ],

    [
        'ced_juridica' => '3014042080',
        'nombre' => 'Municipalidad de Cartago',
        'tipo_id' => $tipoGobiernoLocal->id ?? 1,
        'telefono' => '25504400',
        'correo' => 'portal@municarta.go.cr',
        'urlPageWeb' => 'https://www.municarta.go.cr/',
        'provincia_id' => 3,
        'canton_id' => null,
        'distrito_id' => null,
        'ubi_Lat' => '9.8650198',
        'ubi_long' => '-83.9213406',
        'urlDirectorioTelefonico' => 'https://www.municarta.go.cr/directorioelectronico/#',
        'user_id' => $user->id ?? 1,
    ], [
        'ced_juridica' => '3014042082',
        'nombre' => 'Municipalidad de El Guarco',
        'tipo_id' => $tipoGobiernoLocal->id ?? 1,
        'telefono' => '21064600',
        'correo' => 'contacto@muniguarco.go.cr',
        'urlPageWeb' => 'https://muniguarco.go.cr/',
        'provincia_id' => 3,
        'canton_id' => null,
        'distrito_id' => null,
        'ubi_Lat' => '9.845174',
        'ubi_long' => '-83.9393686',
        'urlDirectorioTelefonico' => 'https://muniguarco.go.cr/directoriotelefonico/',
        'user_id' => $user->id ?? 1,
    ],
    [
        'ced_juridica' => '3014042084',
        'nombre' => 'Municipalidad de Jiménez',
        'tipo_id' => $tipoGobiernoLocal->id ?? 1,
        'telefono' => '25322061',
        'correo' => 'info@munijimenez.go.cr',
        'urlPageWeb' => 'http://munijimenez.go.cr/',
        'provincia_id' => 3,
        'canton_id' => null,
        'distrito_id' => null,
        'ubi_Lat' => '9.8934034',
        'ubi_long' => '-83.7490392',
        'urlDirectorioTelefonico' => 'https://munijimenez.go.cr/index.php/contactenos/directoriotelefonico',
        'user_id' => $user->id ?? 1,
    ],
    [
        'ced_juridica' => '3014042086',
        'nombre' => 'Municipalidad de Paraíso',
        'tipo_id' => $tipoGobiernoLocal->id ?? 1,
        'telefono' => '22208700',
        'correo' => 'info@muniparaiso.go.cr',
        'urlPageWeb' => 'http://www.muniparaiso.go.cr/',
        'provincia_id' => 3,
        'canton_id' => null,
        'distrito_id' => null,
        'ubi_Lat' => '9.8393739',
        'ubi_long' => '-83.868349',
        'urlDirectorioTelefonico' => 'https://www.muniparaiso.go.cr/contactos',
        'user_id' => $user->id ?? 1,
    ],
    [
        'ced_juridica' => '3014042088',
        'nombre' => 'Municipalidad de Turrialba',
        'tipo_id' => $tipoGobiernoLocal->id ?? 1,
        'telefono' => '25560231',
        'correo' => 'recepcion@muniturrialba.go.cr',
        'urlPageWeb' => 'https://www.muniturrialba.go.cr/index.php/en/',
        'provincia_id' => 3,
        'canton_id' => null,
        'distrito_id' => null,
        'ubi_Lat' => '9.9065214',
        'ubi_long' => '-83.6863428',
        'urlDirectorioTelefonico' => 'https://www.muniturrialba.go.cr/index.php/en/mega/layoutbuilder/directorio',
        'user_id' => $user->id ?? 1,
    ],
    [
        'ced_juridica' => '3004045202',
        'nombre' => 'COOPEGUANACASTE R.L',
        'tipo_id' => $tipoCooperativa->id ?? 1,
        'telefono' => '26814700',
        'correo' => 'callcentercg@coopeguanacaste.com',
        'urlPageWeb' => 'https://coopeguanacaste.com/',
        'provincia_id' => 5,
        'canton_id' => null,
        'distrito_id' => null,
        'ubi_Lat' => '10.2697222',
        'ubi_long' => '-85.5733333',
        'urlDirectorioTelefonico' => null,
        'user_id' => $user->id ?? 1,
    ],
    [
        'ced_juridica' => '2100042014',
        'nombre' => 'Ministerio de Ambiente y Energía (MINAE)',
        'tipo_id' => $tipoInstitucionPublica->id ?? 1,
        'telefono' => '26650119',
        'correo' => 'comunicacion@minae.go.cr',
        'urlPageWeb' => 'https://minae.go.cr/',
        'provincia_id' => 5,
        'canton_id' => null,
        'distrito_id' => null,
        'ubi_Lat' => '10.633158',
        'ubi_long' => '-85.4479989',
        'urlDirectorioTelefonico' => null,
        'user_id' => $user->id ?? 1,
    ],
    [
        'ced_juridica' => '3014042089',
        'nombre' => 'Municipalidad de Barva',
        'tipo_id' => $tipoGobiernoLocal->id ?? 1,
        'telefono' => '22603292',
        'correo' => 'alcaldia@munibarva.go.cr',
        'urlPageWeb' => 'https://munibarva.go.cr/',
        'provincia_id' => 4,
        'canton_id' => null,
        'distrito_id' => null,
        'ubi_Lat' => '10.020663',
        'ubi_long' => '-84.1248991',
        'urlDirectorioTelefonico' => 'https://munibarva.go.cr/index.php/departamentos/',
        'user_id' => $user->id ?? 1,
    ],
    [
                'ced_juridica' => '3014042090',
                'nombre' => 'Municipalidad de Belén',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '25870000',
                'correo' => 'servicioalcliente1@belen.go.cr',
                'urlPageWeb' => 'https://www.belen.go.cr/',
                'provincia_id' => 4, // Heredia
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.979224',
                'ubi_long' => '-84.1854632',
                'urlDirectorioTelefonico' => 'https://www.belen.go.cr/directorioinstitucional',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042091',
                'nombre' => 'Municipalidad de Flores',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '22657109',
                'correo' => 'info@flores.go.cr',
                'urlPageWeb' => 'https://flores.go.cr/',
                'provincia_id' => 4, // Heredia
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '10.0029041',
                'ubi_long' => '-84.1519869',
                'urlDirectorioTelefonico' => 'https://flores.go.cr/contactenos/directorio/',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042092',
                'nombre' => 'Municipalidad de Heredia',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '22771424',
                'correo' => 'comunicacion@heredia.go.cr',
                'urlPageWeb' => 'https://www.heredia.go.cr/es',
                'provincia_id' => 4, // Heredia
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.9989622',
                'ubi_long' => '-84.1173807',
                'urlDirectorioTelefonico' => 'https://www.heredia.go.cr/es/contactenos/directoriotelefonico',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3002665546',
                'nombre' => 'Municipalidad de San Isidro',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '22688104',
                'correo' => 'info@sanisidro.go.cr',
                'urlPageWeb' => 'https://www.munisanisidro.go.cr/',
                'provincia_id' => 4, // Heredia
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '10.0162078',
                'ubi_long' => '-84.0579414',
                'urlDirectorioTelefonico' => 'https://www.munisanisidro.go.cr/index.php/contactenos/directoriointerno',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042094',
                'nombre' => 'Municipalidad de San Pablo',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '22770700',
                'correo' => 'alcaldia@sanpablo.go.cr',
                'urlPageWeb' => 'https://www.sanpablo.go.cr/',
                'provincia_id' => 4, // Heredia
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.9946667',
                'ubi_long' => '-84.0996431',
                'urlDirectorioTelefonico' => 'https://www.sanpablo.go.cr/listacontactos/',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042095',
                'nombre' => 'Municipalidad de San Rafael',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '22370789',
                'correo' => 'info@munisrh.go.cr',
                'urlPageWeb' => 'https://www.munisrh.go.cr/',
                'provincia_id' => 4, // Heredia
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '10.0142919',
                'ubi_long' => '-84.1025972',
                'urlDirectorioTelefonico' => 'https://www.munisrh.go.cr/contacto/directoriotelefonico/',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042096',
                'nombre' => 'Municipalidad de Santa Bárbara',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '22699081',
                'correo' => 'informacion@santabarbara.go.cr',
                'urlPageWeb' => 'https://www.santabarbara.go.cr/',
                'provincia_id' => 4, // Heredia
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '10.0373526',
                'ubi_long' => '-84.1597485',
                'urlDirectorioTelefonico' => 'https://www.santabarbara.go.cr/index.php/conozcanos/mimunicipalidad/directoriotelefonico.html',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042097',
                'nombre' => 'Municipalidad de Santo Domingo',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '22440117',
                'correo' => 'info@munisantodomingo.go.cr',
                'urlPageWeb' => 'https://www.munisantodomingo.go.cr/',
                'provincia_id' => 4, // Heredia
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.9804832',
                'ubi_long' => '-84.0939113',
                'urlDirectorioTelefonico' => 'https://www.munisantodomingo.go.cr/',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042098',
                'nombre' => 'Municipalidad de Sarapiquí',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '40006700',
                'correo' => 'municipalidad@sarapiqui.go.cr',
                'urlPageWeb' => 'https://www.sarapiqui.go.cr/',
                'provincia_id' => 4, // Heredia
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '10.4499664',
                'ubi_long' => '-84.0157305',
                'urlDirectorioTelefonico' => 'https://www.sarapiqui.go.cr/directorio/',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042122',
                'nombre' => 'Municipalidad de Guácimo',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '27165051',
                'correo' => 'info@guacimo.go.cr',
                'urlPageWeb' => 'http://www.guacimo.go.cr',
                'provincia_id' => 6, // Limón
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '10.209002',
                'ubi_long' => '-83.6843641',
                'urlDirectorioTelefonico' => 'https://guacimo.go.cr/index.php/es/mas/directoriotelefonico',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042123',
                'nombre' => 'Municipalidad de Limón',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '27584444',
                'correo' => 'alcaldia@municlimon.go.cr',
                'urlPageWeb' => 'http://www.municlimon.go.cr',
                'provincia_id' => 6, // Limón
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.9923092',
                'ubi_long' => '-83.0360862',
                'urlDirectorioTelefonico' => 'https://www.municlimon.go.cr/index.php/mnconozcanos/mnmimunicipalidad/mndirectoriotelefonico.html',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042148',
                'nombre' => 'Municipalidad de Matina',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '27181360',
                'correo' => 'info@munimatina.go.cr',
                'urlPageWeb' => 'https://www.munimatina.go.cr',
                'provincia_id' => 6, // Limón
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '10.0767697',
                'ubi_long' => '-83.29204',
                'urlDirectorioTelefonico' => 'https://www.munimatina.go.cr/index.php/mncontactenos/directoriotelefonico',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042833',
                'nombre' => 'Municipalidad de Pococí', // Corregido: "Pococa" a "Pococí"
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '27136560',
                'correo' => 'secretaria@munipococi.go.cr',
                'urlPageWeb' => 'http://www.munipococi.go.cr',
                'provincia_id' => 6, // Limón
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '10.2028164',
                'ubi_long' => '-83.7917509',
                'urlDirectorioTelefonico' => 'https://munipococi.go.cr/index/index.php/contacto/mndirectoriotelefonico',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042126',
                'nombre' => 'Municipalidad de Siquirres',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '27686266',
                'correo' => 'info@siquirres.go.cr',
                'urlPageWeb' => 'https://siquirres.go.cr/',
                'provincia_id' => 6, // Limón
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '10.0983655',
                'ubi_long' => '-83.5057293',
                'urlDirectorioTelefonico' => 'https://siquirres.go.cr/directoriotelefonico/',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042112',
                'nombre' => 'Municipalidad de Buenos Aires',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '27302422',
                'correo' => 'informacion@mba.go.cr',
                'urlPageWeb' => 'https://munibuenosaires.go.cr/',
                'provincia_id' => 5, // Puntarenas
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.172645790616688',
                'ubi_long' => '-83.335328082788',
                'urlDirectorioTelefonico' => 'https://munibuenosaires.go.cr/directoriotelefonico/',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042114',
                'nombre' => 'Municipalidad de Corredores',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '27833939',
                'correo' => 'recepcion@municipalidadcorredores.go.cr',
                'urlPageWeb' => 'https://www.municorredores.go.cr/',
                'provincia_id' => 5, // Puntarenas
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '8.649356121022912',
                'ubi_long' => '-82.94184279203058',
                'urlDirectorioTelefonico' => 'https://www.municorredores.go.cr/directorio/',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042113',
                'nombre' => 'Municipalidad de Coto Brus',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '27733128',
                'correo' => 'info@municotobrus.go.cr',
                'urlPageWeb' => 'https://www.municotobrus.go.cr/',
                'provincia_id' => 5, // Puntarenas
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '8.82012864238029',
                'ubi_long' => '-82.97023094600479',
                'urlDirectorioTelefonico' => 'https://www.municotobrus.go.cr/contactos',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014043195',
                'nombre' => 'Municipalidad de Esparza',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '26360100',
                'correo' => 'info@muniesparza.go.cr',
                'urlPageWeb' => 'https://muniesparza.go.cr/',
                'provincia_id' => 5, // Puntarenas
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.99196708337074',
                'ubi_long' => '-84.66787721900374',
                'urlDirectorioTelefonico' => 'https://muniesparza.go.cr/contactos',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014056076',
                'nombre' => 'Municipalidad de Garabito',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '24592800',
                'correo' => 'serviciosciudadanos@munigarabito.go.cr',
                'urlPageWeb' => 'https://www.munigarabito.go.cr/',
                'provincia_id' => 5, // Puntarenas
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.61020969079953',
                'ubi_long' => '-84.62226715153837',
                'urlDirectorioTelefonico' => 'https://www.munigarabito.go.cr/organizacioninstitucional/contactos',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042116',
                'nombre' => 'Municipalidad de Golfito',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '27750080',
                'correo' => 'plataforma@munidegolfito.go.cr',
                'urlPageWeb' => 'https://munidegolfito.go.cr/',
                'provincia_id' => 5, // Puntarenas
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '8.625646533714118',
                'ubi_long' => '-83.15355487114718',
                'urlDirectorioTelefonico' => 'https://munidegolfito.go.cr/index.php/mncontactenos/correosytelefonos',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042118',
                'nombre' => 'Municipalidad de Montes de Oro',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '-89916297',
                'correo' => 'info@munimontesdeoro.go.cr',
                'urlPageWeb' => 'https://munimontesdeoro.go.cr/',
                'provincia_id' => 5, // Puntarenas
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '10.091929478544541',
                'ubi_long' => '-84.72876941346021',
                'urlDirectorioTelefonico' => 'https://munimontesdeoro.go.cr/departamentos/',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042119',
                'nombre' => 'Municipalidad de Osa',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '27820000',
                'correo' => 'info@munideosa.go.cr',
                'urlPageWeb' => 'https://www.gobiernolocalosa.go.cr/',
                'provincia_id' => 5, // Puntarenas
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '8.979371551370917',
                'ubi_long' => '-83.53272391716771',
                'urlDirectorioTelefonico' => null, // Vacío en los datos originales
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3007327490',
                'nombre' => 'Municipalidad de Monteverde',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '26456909',
                'correo' => 'info@monteverde.go.cr',
                'urlPageWeb' => 'https://monteverde.go.cr/',
                'provincia_id' => 5, // Puntarenas
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '10.318202027080332',
                'ubi_long' => '-84.82391230184743',
                'urlDirectorioTelefonico' => null, // Vacío en los datos originales
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042121',
                'nombre' => 'Municipalidad de Parrita',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '27778400',
                'correo' => 'plataforma@muniparrita.go.cr',
                'urlPageWeb' => 'https://www.muniparrita.go.cr/',
                'provincia_id' => 5, // Puntarenas
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.529510015723366',
                'ubi_long' => '-84.36203722023758',
                'urlDirectorioTelefonico' => 'https://www.muniparrita.go.cr/directorio/',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042120',
                'nombre' => 'Municipalidad de Puntarenas',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '26610250',
                'correo' => 'alcaldia@munipuntarenas.go.cr',
                'urlPageWeb' => 'https://www.puntarenas.go.cr/',
                'provincia_id' => 5, // Puntarenas
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.976538271229144',
                'ubi_long' => '-84.83619288524885',
                'urlDirectorioTelefonico' => 'https://www.puntarenas.go.cr/contactos',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042111',
                'nombre' => 'Municipalidad de Quepos',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '27778300',
                'correo' => 'secretariaalcaldia@muniquepos.go.cr',
                'urlPageWeb' => 'https://muniquepos.go.cr/',
                'provincia_id' => 5, // Puntarenas
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.431591950592141',
                'ubi_long' => '-84.16269356503436',
                'urlDirectorioTelefonico' => 'https://muniquepos.go.cr/telefonos/',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042043',
                'nombre' => 'Municipalidad de Acosta',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '24100186',
                'correo' => 'plataforma@acosta.go.cr',
                'urlPageWeb' => 'https://www.acosta.go.cr/',
                'provincia_id' => 1, // San José
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.7989664',
                'ubi_long' => '-84.1640918',
                'urlDirectorioTelefonico' => 'https://www.acosta.go.cr/index.php/contactenos',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014043291',
                'nombre' => 'Municipalidad de Alajuelita',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '22546002',
                'correo' => 'rsiles@munialajuelita.go.cr',
                'urlPageWeb' => 'https://www.munialajuelita.go.cr/',
                'provincia_id' => 1, // San José
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.9033668',
                'ubi_long' => '-84.1002115',
                'urlDirectorioTelefonico' => 'https://www.munialajuelita.go.cr/index.php/conozcanos/mimunicipalidad/directoriotelefonico',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042045', // Nota: formato diferente
                'nombre' => 'Municipalidad de Aserrí',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '22303078',
                'correo' => 'consultas@aserri.go.cr',
                'urlPageWeb' => 'https://aserri.go.cr/',
                'provincia_id' => 1, // San José
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.8626824',
                'ubi_long' => '-84.0958266',
                'urlDirectorioTelefonico' => 'https://aserri.go.cr/contactenos/',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042047',
                'nombre' => 'Municipalidad de Curridabat',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '22165200',
                'correo' => 'alcaldia@curridabat.go.cr',
                'urlPageWeb' => 'https://www.curridabat.go.cr/',
                'provincia_id' => 1, // San José
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.9155602',
                'ubi_long' => '-84.0395967',
                'urlDirectorioTelefonico' => 'https://www.curridabat.go.cr/inicio/contacto/',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042048',
                'nombre' => 'Municipalidad de Desamparados',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '22173500',
                'correo' => 'comunicacion@desamparados.go.cr',
                'urlPageWeb' => 'https://www.desamparados.go.cr/es',
                'provincia_id' => 1, // San José
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.8986351',
                'ubi_long' => '-84.0655143',
                'urlDirectorioTelefonico' => 'https://virtual.desamparados.go.cr:2121/jpcloud/public/agendaExterna',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042049',
                'nombre' => 'Municipalidad de Dota',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '25412717',
                'correo' => 'alex.diaz@dota.go.cr',
                'urlPageWeb' => 'https://dota.go.cr/contacto/',
                'provincia_id' => 1, // San José
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.6532948',
                'ubi_long' => '-83.9696443',
                'urlDirectorioTelefonico' => 'https://dota.go.cr/contacto/',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042050',
                'nombre' => 'Municipalidad de Escazú',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '22087500',
                'correo' => 'comunicacion@escazu.go.cr',
                'urlPageWeb' => 'https://www.escazu.go.cr/',
                'provincia_id' => 1, // San José
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.9204346',
                'ubi_long' => '-84.140523',
                'urlDirectorioTelefonico' => 'https://www.escazu.go.cr/contactenos',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042051',
                'nombre' => 'Municipalidad de Goicoechea',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '25276600',
                'correo' => 'alcaldia@munigoicoechea.go.cr',
                'urlPageWeb' => 'https://munigoicoechea.go.cr/inicio/',
                'provincia_id' => 1, // San José
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.9455969',
                'ubi_long' => '-84.0567701',
                'urlDirectorioTelefonico' => 'https://munigoicoechea.go.cr/inicio/guiatelefonica/',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042052',
                'nombre' => 'Municipalidad de León Cortés Castro',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '25461201',
                'correo' => 'info@munileco.go.cr',
                'urlPageWeb' => 'https://munileco.go.cr/',
                'provincia_id' => 1, // San José
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.6836354',
                'ubi_long' => '-84.0418806',
                'urlDirectorioTelefonico' => 'https://munileco.go.cr/directoriointerno/',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042053',
                'nombre' => 'Municipalidad de Montes de Oca',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '22805589',
                'correo' => 'concejo@montesdeoca.go.cr',
                'urlPageWeb' => 'https://montesdeoca.go.cr/',
                'provincia_id' => 1, // San José
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.9335645',
                'ubi_long' => '-84.0570789',
                'urlDirectorioTelefonico' => 'https://montesdeoca.go.cr/contactenos/directorio_interno.aspx',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042054',
                'nombre' => 'Municipalidad de Mora',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '24592500',
                'correo' => 'info@mora.go.cr',
                'urlPageWeb' => 'https://mora.go.cr/',
                'provincia_id' => 1, // San José
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.9161283',
                'ubi_long' => '-84.2426705',
                'urlDirectorioTelefonico' => 'https://mora.go.cr/directoriodecontactos2/',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042055',
                'nombre' => 'Municipalidad de Moravia',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '25074000',
                'correo' => 'walpizar@moravia.go.cr',
                'urlPageWeb' => 'https://moravia.go.cr/',
                'provincia_id' => 1, // San José
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.9610139',
                'ubi_long' => '-84.0477318',
                'urlDirectorioTelefonico' => 'https://moravia.go.cr/contactenos/directoriotelefonico/',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042057',
                'nombre' => 'Municipalidad de Puriscal',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '24166026',
                'correo' => 'informacion@puriscal.go.cr',
                'urlPageWeb' => 'https://www.puriscal.go.cr/',
                'provincia_id' => 1, // San José
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.8473516',
                'ubi_long' => '-84.3145736',
                'urlDirectorioTelefonico' => 'https://www.puriscal.go.cr/contactamos/',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042058',
                'nombre' => 'Municipalidad de San José',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '25476000',
                'correo' => 'porusted@msj.go.cr',
                'urlPageWeb' => 'https://www.msj.go.cr/cont/Paginas/default.aspx',
                'provincia_id' => 1, // San José
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.9256551',
                'ubi_long' => '-84.1106381',
                'urlDirectorioTelefonico' => 'https://www.msj.go.cr/SiteAssets/GUIA%20TELEFONICA%20INTERACTIVA%202022.xls',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042059',
                'nombre' => 'Municipalidad de Santa Ana',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '25827200',
                'correo' => 'info@santaana.go.cr',
                'urlPageWeb' => 'https://www.santaana.go.cr/',
                'provincia_id' => 1, // San José
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.9331251',
                'ubi_long' => '-84.181241',
                'urlDirectorioTelefonico' => 'https://www.santaana.go.cr/telefonosinteres/',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042060', // Nota: formato diferente
                'nombre' => 'Municipalidad de Tarrazú',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '25466227',
                'correo' => 'alcaldia@munitarrazu.go.cr',
                'urlPageWeb' => 'https://www.munis.cr/municipalidaddetarrazu',
                'provincia_id' => 1, // San José
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.658884',
                'ubi_long' => '-84.0219503',
                'urlDirectorioTelefonico' => null, // Vacío en los datos originales
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042061',
                'nombre' => 'Municipalidad de Tibás',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '22406070',
                'correo' => 'info@munitibas.go.cr',
                'urlPageWeb' => 'https://munitibas.go.cr/',
                'provincia_id' => 1, // San José
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.9622913',
                'ubi_long' => '-84.0774147',
                'urlDirectorioTelefonico' => 'https://munitibas.go.cr/contactos',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014042062',
                'nombre' => 'Municipalidad de Turrubares',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '24190445',
                'correo' => 'info@turrubares.go.cr',
                'urlPageWeb' => 'https://turrubares.go.cr/index.php',
                'provincia_id' => 1, // San José
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.9084339',
                'ubi_long' => '-84.441056',
                'urlDirectorioTelefonico' => 'https://turrubares.go.cr/index.php/conozcanos/mimunicipalidad/directoriotelefonico',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3014045149', // Nota: formato diferente
                'nombre' => 'Municipalidad de Vázquez de Coronado',
                'tipo_id' => $tipoGobiernoLocal->id ?? 1,
                'telefono' => '22160600',
                'correo' => 'plataformaservicios@coromuni.go.cr',
                'urlPageWeb' => 'https://www.coromuni.go.cr/',
                'provincia_id' => 1, // San José
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.9767084',
                'ubi_long' => '-84.0075788',
                'urlDirectorioTelefonico' => 'https://coromuni.go.cr/directorio',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3013045269',
                'nombre' => 'Organización de Estudios Tropicales  OTS',
                'tipo_id' => $tipoConsorcio->id ?? 2, // Asumiendo ID 2 para Consorcio
                'telefono' => '25240607',
                'correo' => 'costarica@tropicalstudies.org',
                'urlPageWeb' => 'https://tropicalstudies.org/',
                'provincia_id' => 1, // San José
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '10.4311747',
                'ubi_long' => '-84.0036591',
                'urlDirectorioTelefonico' => 'https://tropicalstudies.org/portfolio/contactus/',
                'user_id' => $user->id ?? 1,
            ],
            [
                'ced_juridica' => '3007231686',
                'nombre' => 'Consejo Nacional de Vialidad CONAVI',
                'tipo_id' => $tipoInstitucionPublica->id ?? 3, // Asumiendo ID 3 para Institución pública
                'telefono' => '22027000',
                'correo' => 'contraloria.servicios@conavi.go.cr',
                'urlPageWeb' => 'https://conavi.go.cr',
                'provincia_id' => 1, // San José
                'canton_id' => null,
                'distrito_id' => null,
                'ubi_Lat' => '9.940156022381549',
                'ubi_long' => '-84.05225921703538',
                'urlDirectorioTelefonico' => 'https://conavi.go.cr/directoriotelef%C3%B3nico',
                'user_id' => $user->id ?? 1,
            ],

        ];

        foreach ($organizaciones as $org) {
            Organizacion::create($org);
        }

        $this->command->info('✓ ' . count($organizaciones) . ' organizaciones de prueba creadas exitosamente.');
    }
}
